development:
  adapter: postgresql
  database: my_app_development
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: 123

test:
  adapter: postgresql
  database: my_app_test
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: 123

production:
  adapter: postgresql
  database: my_app_production
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: 123

